name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs: 
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Metric Collector
        run: |
          RELEASE_VERSION="${GITHUB_REF##*/}"
          RELEASE_VERSION="${RELEASE_VERSION:1}"
          ./make_package.sh "$RELEASE_VERSION"

          cd package-${RELEASE_VERSION}
          assets=()
          for asset in *.{gz,zip}; do
            new_asset="${asset/%.tar.gz/_amd64.tar.gz}"
            new_asset="${new_asset/%.zip/_amd64.zip}"
            mv "$asset" "$new_asset"
            assets+=("-a" "$new_asset")
          done
      
          hub release create "${assets[@]}" -m "v$RELEASE_VERSION" "v$RELEASE_VERSION"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      